name: "tsql_utils_dbt_audit_helper_integration_tests"
version: "1.0"
config-version: 2

profile: "integration_tests"

dispatch:
  - macro_namespace: audit_helper
    search_order:
      [
        "tsql_utils_dbt_audit_helper_integration_tests",
        "tsql_utils",
        "audit_helper",
      ]

models:
  audit_helper_integration_tests:
    materialized: table
