
name: 'tsql_utils_dbt_utils_integration_tests'
version: '1.0'
config-version: 2

profile: 'integration_tests'

source-paths: ["models"]
analysis-paths: ["analysis"] 
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"
    
vars:
  dbt_utils_dispatch_list: ['tsql_utils']

models:
  dbt_utils_integration_tests:
    +enabled: true
    cross_db_utils:
      test_dateadd: &disabled
        +enabled: false
      test_datediff: *disabled
      test_hash: *disabled
      test_last_day: *disabled
      test_split_part:
        +enabled: "{{ target.name != 'synapse' }}"
    datetime:
      test_date_spine: *disabled
    materializations: *disabled
      
    schema_tests:
      data_test_mutually_exclusive_ranges_no_gaps: *disabled
      data_test_mutually_exclusive_ranges_with_gaps: *disabled
      data_test_not_constant: *disabled
      data_test_relationships_where_table_2: *disabled
      data_test_unique_where: *disabled
      data_test_not_null_where: *disabled
      # the following work but only when
      # the dbt-utils submodule macros are overwritten 
      data_test_at_least_one: *disabled
      data_people: *disabled
      data_test_expression_is_true: *disabled
      data_test_not_constant: *disabled
    sql:
      test_generate_series: *disabled
      test_get_column_values: *disabled
      test_get_relations_by_pattern: *disabled
      test_get_relations_by_prefix_and_union: *disabled
      test_groupby: *disabled
      get_query_results_as_dict: *disabled
      test_surrogate_key: *disabled
      test_union: *disabled
    web:
      test_url_host: *disabled
      test_url_path: *disabled
      test_urls: *disabled

seeds:

  +quote_columns: false
  dbt_utils_integration_tests:

    cross_db:
      data_date_trunc:
        +column_types:
          updated_at: datetime
          day: date
          month: date
      data_split_part:
        +enabled: "{{ target.name != 'synapse' }}"

      data_dateadd:
        +column_types:
          from_time: datetime
          result: datetime

      data_datediff:
        +column_types:
          first_date: datetime
          second_date: datetime