---
name: Integration tests on SQL Server
on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - v*

jobs:
  integration-tests-sqlserver:
    name: Integration tests on SQL Server
    strategy:
      matrix:
        sqlserver_version: ["2017", "2019", "2022"]
        dbt_package:
          ["dbt-audit-helper", "dbt-date", "dbt-expectations", "dbt-utils"]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dbt-msft/dbt-sqlserver:CI-3.10-msodbc18
    services:
      sqlserver:
        image: ghcr.io/dbt-msft/dbt-sqlserver:server-${{ matrix.sqlserver_version }}
        env:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: 5atyaNadella
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: pip install -r dev_requirements.txt

      - name: Copy profiles
        run: cp integration_tests/ci/sample.profiles.yml ~/.dbt/profiles.yml

      - name: Run integration tests
        run: |
          cd integration_tests/${{ matrix.dbt_package }}
          dbt deps --target sqlserver
          dbt seed --target sqlserver --full-refresh
          dbt run --target sqlserver --full-refresh
          dbt test --target sqlserver
