---
name: Integration tests on SQL Server
on: # yamllint disable-line rule:truthy
  push:
    branches:
      - master
      - v*

jobs:
  integration-tests-sqlserver:
    name: Integration tests on SQL Server
    strategy:
      matrix:
        sqlserver_version: ["2017", "2019", "2022"]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dbt-sqlserver:CI-3.10-msodbc18
    services:
      sqlserver:
        image: ghcr.io/dbt-sqlserver:server-${{ matrix.sqlserver_version }}
        env:
          ACCEPT_EULA: "Y"
          SA_PASSWORD: 5atyaNadella
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install dependencies
        run: pip install -r dev_requirements.txt
